services:
  db:
    image: pgvector/pgvector:pg16
    container_name: drivelocal_db
    restart: always
    environment:
      POSTGRES_DB: drivelocal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: